import type {
  FeeSummary,
  MediaPreview,
  PresentationBundle,
  VideoCapability,
} from '@/shared/api/contracts/media'
export const videoCapability: VideoCapability = {
  id: 'video-native',
  version: 1,
  configurationHash: 'video-config',
  provider: 'registered',
  accountNamespace: 'server-account',
  model: '登记视频模型',
  region: 'cn',
  durations: [5, 10],
  resolutions: ['720p', '1080p'],
  audioModes: ['NATIVE', 'NONE'],
  prices: {
    '720p': {
      ref: 'price-1',
      version: 'v1',
      currency: 'CNY',
      unit: 'PER_SECOND',
      effectiveAt: '2026-10-05T00:00:00Z',
      inputRate: '0.1',
      outputRate: '0',
    },
  },
  verificationStatus: 'PROTOCOL_TESTED',
  pollIntervalSeconds: 10,
  maxPolls: 20,
}
export const fee: FeeSummary = {
  kind: 'TASK',
  resourceId: '51',
  currency: 'CNY',
  limitAmount: '20.00000000',
  estimatedAmount: '0.12500001',
  reservedAmount: '2.00000000',
  providerInputTokens: 120,
  providerOutputTokens: 40,
  reservedTokens: 600,
  attempts: 3,
  settledAttempts: 1,
  unknownAttempts: 1,
  pendingAttempts: 1,
  simulatedAttempts: 0,
  legacyUntrackedAttempts: 0,
  overLimit: false,
  costStatus: 'UNKNOWN',
}
export const mediaPreview: MediaPreview = {
  contentPlan: {
    planHash: 'a'.repeat(64),
    title: '资料驱动水循环',
    contentSlides: 1,
    sourceSlides: 2,
    totalSlides: 3,
  },
  taskId: 51,
  previewVersion: 1,
  planVersion: 1,
  hash: 'preview-hash',
  status: 'WAITING',
  approvalId: 'media-approval-1',
  expiresAt: '2099-01-01T00:00:00Z',
  configurationHash: 'configuration',
  currency: 'CNY',
  estimatedAmount: '2.00000000',
  maximumAmount: '20.00000000',
  units: [
    {
      unitId: 'slide1',
      title: '理解水循环',
      text: '水汽遇冷，凝成水滴。',
      notes: '说明凝结过程',
      layout: 'TEXT',
      imageMode: 'NONE',
      imagePrompt: '',
      references: ['D101v1'],
      seconds: 0,
    },
  ],
  sourceDependencies: [{ knowledgeBaseId: 12, documentId: 101, documentVersion: 1 }],
  coverage: [],
  catalogs: [],
  assets: [],
  qualityStatus: 'REQUIRES_HUMAN_REVIEW',
  storyboard: null,
}
export const presentation: PresentationBundle = {
  pptx: {
    storageKey: 'private/file.pptx',
    mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    size: 100,
    checksum: 'pptx-checksum',
  },
  artifactId: 91,
  pages: [
    {
      number: 1,
      unitId: 'slide1',
      preview: {
        storageKey: 'private/page.png',
        mime: 'image/png',
        size: 50,
        checksum: 'png-checksum',
      },
      artifactId: 92,
    },
  ],
  check: {
    taskId: 51,
    previewVersion: 1,
    planVersion: 1,
    approvalHash: 'approved',
    inputHash: 'input',
    layoutVersion: 'pptx-layout-v1',
    font: 'Microsoft YaHei',
    slideCount: 2,
    structuralStatus: 'PASSED',
    qualityStatus: 'REQUIRES_HUMAN_REVIEW',
    warnings: [],
    images: [],
    sources: mediaPreview.sourceDependencies,
    coverage: [],
  },
}
