import type {
  SessionSnapshot,
  IngestionMetadata,
  SectionPage,
  TaskPlanSnapshot,
  TraceGraph,
  TaskSnapshot,
} from '@/shared/api/contracts/backend'
import { task, user } from './fixtures'
const time = '2026-10-04T00:00:00Z'
export const session: SessionSnapshot = {
  id: 701,
  title: '备份规则',
  version: 1,
  scope: { mode: 'SELF', knowledgeBaseIds: [], ownerUserId: null },
  createdAt: time,
  updatedAt: time,
}
export const ingestion: IngestionMetadata = {
  documentId: 101,
  documentVersion: 1,
  activeProcessingRevision: 1,
  ingestionId: 9,
  processingRevision: 3,
  status: 'FAILED',
  errorCode: 'SEARCH_UNAVAILABLE',
  expectedChunkCount: 2,
  configHash: 'hash',
  parserVersion: 'v1',
  splitPolicyVersion: 'v1',
  mappingVersion: 'v1',
  tokenizerRef: 'bytes',
  countSource: 'ESTIMATED_UTF8_BYTES',
  progress: {
    phase: 'INDEXING',
    failureStage: 'INDEXING',
    claims: 1,
    modelAttempts: 1,
    reservedInputTokens: 20,
    actualInputTokens: 10,
    unknownUsageAttempts: 0,
    deadline: '2099-01-01T00:00:00Z',
    nextAttemptAt: null,
    retryable: true,
    plannedBatches: 1,
    embeddedBatches: 1,
    indexedBatches: 0,
    unknownBatches: 0,
    peakVectorItems: 2,
  },
}
export const sectionPage: SectionPage = {
  documentId: 101,
  documentVersion: 1,
  processingRevision: 1,
  sectionId: 's1',
  headingPath: '步骤',
  sectionStartOffset: 0,
  sectionEndOffset: 20,
  startOffset: 0,
  endOffset: 5,
  text: '知识与验证',
  nextOffset: 5,
  complete: false,
  remainingStartOffset: 5,
  remainingEndOffset: 20,
  tokenCount: 15,
  countSource: 'ESTIMATED_UTF8_BYTES',
}
export const plan: TaskPlanSnapshot = {
  plan: {
    version: 'plan-s05-v1',
    steps: [
      {
        stepId: 'research',
        action: 'research',
        agentId: 'ResearchWorker',
        taskType: 'RESEARCH_REPORT',
        dependsOn: [],
        input: { focus: '核对备份规则' },
        qualityRequirement: 'SOURCE_GROUNDED',
      },
      {
        stepId: 'analysis',
        action: 'analysis',
        agentId: 'AnalysisWorker',
        taskType: 'RESEARCH_REPORT',
        dependsOn: [],
        input: { focus: '分析资料' },
        qualityRequirement: 'SOURCE_GROUNDED',
      },
      {
        stepId: 'report',
        action: 'report',
        agentId: 'ReportWriter',
        taskType: 'RESEARCH_REPORT',
        dependsOn: ['research', 'analysis'],
        input: { focus: '整理报告' },
        qualityRequirement: 'SOURCE_GROUNDED',
      },
    ],
  },
  planHash: 'test-plan-hash',
  agentVersion: 's05-v1',
  modelId: 'primary',
  policyVersion: 'v1',
}
const node = {
  spanId: 'root',
  parentSpanId: null,
  type: 'ROOT',
  name: '问答执行',
  stepId: null,
  agentId: null,
  dependsOn: [],
  sequence: 1,
  status: 'SUCCESS',
  startedAt: time,
  endedAt: '2026-10-04T00:00:02Z',
  errorCode: null,
  modelId: null,
  taskType: null,
  profile: null,
  policyVersion: null,
  routeReason: null,
  attempt: 0,
  inputTokens: null,
  outputTokens: null,
  usageSource: null,
  toolCallHash: null,
}
export const graph: TraceGraph = {
  run: {
    traceId: 'trace-1',
    actorUserId: user.id,
    status: 'SUCCESS',
    modelId: 'primary',
    attempts: 1,
    mock: true,
    createdAt: time,
    endedAt: '2026-10-04T00:00:02Z',
    previousTraceId: 'trace-old',
    nodeCount: 3,
    incomplete: false,
    telemetryDropped: false,
    firstDeliverableAt: '2026-10-04T00:00:02Z',
  },
  nodes: [
    node,
    {
      ...node,
      spanId: 'model',
      parentSpanId: 'root',
      type: 'MODEL',
      name: '模型调用',
      sequence: 2,
      inputTokens: 10,
      outputTokens: 5,
      usageSource: 'PROVIDER',
      modelId: 'primary',
      attempt: 1,
    },
    {
      ...node,
      spanId: 'tool',
      parentSpanId: 'root',
      type: 'TOOL',
      name: '工具核验',
      sequence: 3,
      dependsOn: ['model'],
      status: 'REUSED',
    },
  ],
  edges: [
    { from: 'root', to: 'model', kind: 'CALL' },
    { from: 'model', to: 'tool', kind: 'DEPENDENCY' },
  ],
  missingNodeIds: [],
  incomplete: false,
  costStatus: 'UNKNOWN',
}
export const modernTask: TaskSnapshot = {
  ...task,
  taskType: 'RESEARCH_REPORT',
  status: 'RUNNING',
  progress: {
    stage: 'ANALYZING',
    message: '正在执行：整理资料要点、统计与分析',
    workerEnabled: true,
    executionActive: true,
    completedSteps: 1,
    totalSteps: 5,
    percent: 20,
    currentSteps: ['research', 'analysis'],
    steps: ['prepare', 'research', 'analysis', 'report', 'publish'].map((stepId, index) => ({
      stepId,
      label: ['读取并核验资料', '整理资料要点', '统计与分析', '生成报告', '校验并发布结果'][index]!,
      status: index === 0 ? 'SUCCEEDED' : index < 3 ? 'RUNNING' : 'PENDING',
      startedAt: index < 3 ? time : null,
      completedAt: index === 0 ? time : null,
      errorCode: null,
    })),
    startedAt: time,
    updatedAt: time,
    lastHeartbeatAt: time,
    elapsedExecutionSeconds: 12,
    pollAfterMillis: 2000,
  },
  coverage: [
    {
      documentId: 101,
      documentVersion: 1,
      processingRevision: 1,
      sectionId: 's1',
      completedPages: 1,
      readStartOffset: 0,
      readEndOffset: 5,
      remainingStartOffset: 5,
      remainingEndOffset: 20,
      complete: false,
      countSource: 'ESTIMATED_UTF8_BYTES',
    },
  ],
}
